const state = { nodes: [], edges: [], mode: 'network', positions: new Map() };
const $ = (selector) => document.querySelector(selector);
function parseTsv(text) { return text.split(/\r?\n/).filter((line) => line && !line.startsWith('#') && line.split('\t')[0] !== 'node_id').map((line) => line.split('\t')); }
async function loadData() { const [nodesResponse, edgesResponse] = await Promise.all([fetch('data/week1_nodes.tsv'), fetch('data/week1_edges.tsv')]); const nodeRows = parseTsv(await nodesResponse.text()); const edgeRows = parseTsv(await edgesResponse.text()); const nodeMap = new Map(nodeRows.map((row) => [row[0], { id: row[0], name: row[1] || row[0].replaceAll('_', ' '), url: row[3] || `https://en.wikipedia.org/wiki/${row[0]}`, inDegree: 0, outDegree: 0 }])); state.edges = edgeRows.map(([source, target]) => ({ source, target })).filter((edge) => nodeMap.has(edge.source) && nodeMap.has(edge.target)); state.edges.forEach(({ source, target }) => { nodeMap.get(source).outDegree += 1; nodeMap.get(target).inDegree += 1; }); state.nodes = [...nodeMap.values()].map((node) => ({ ...node, totalDegree: node.inDegree + node.outDegree })); renderStats(); renderRanking(); renderFinding(); $('#loading').remove(); resizeCanvas(); draw(); }
function renderStats() { const isolates = state.nodes.filter((node) => node.totalDegree === 0).length; const density = state.edges.length / (state.nodes.length * (state.nodes.length - 1)); $('#node-count').textContent = state.nodes.length; $('#edge-count').textContent = state.edges.length.toLocaleString(); $('#isolate-count').textContent = isolates; $('#density-value').textContent = `${(density * 100).toFixed(1)}%`; }
function renderRanking() { const top = [...state.nodes].sort((a, b) => b.inDegree - a.inDegree).slice(0, 8); $('#ranking-table').innerHTML = top.map((node, index) => `<div class="rank-row"><span>${String(index + 1).padStart(2, '0')}</span><span class="rank-name"><a href="${node.url}" target="_blank" rel="noreferrer">${node.name}</a></span><span class="rank-score">${node.inDegree}<small>IN</small></span><span class="rank-score">${node.outDegree}<small>OUT</small></span></div>`).join(''); }
function renderFinding() { const topIn = [...state.nodes].sort((a, b) => b.inDegree - a.inDegree)[0]; const topOut = [...state.nodes].sort((a, b) => b.outDegree - a.outDegree)[0]; $('#finding-copy').textContent = `${topIn.name} is the most linked-to character with ${topIn.inDegree} incoming links. ${topOut.name} points outward most often (${topOut.outDegree} links), a reminder that being central can mean being talked about or doing the talking.`; }
function resizeCanvas() { const canvas = $('#network-canvas'); const rect = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; canvas.width = rect.width * ratio; canvas.height = rect.height * ratio; canvas.getContext('2d').setTransform(ratio, 0, 0, ratio, 0, 0); }
function getPosition(node, index, width, height) { if (!state.positions.has(node.id)) { const angle = index * 2.39996; const radius = Math.min(width, height) * (.1 + Math.sqrt(index / state.nodes.length) * .42); state.positions.set(node.id, { x: width / 2 + Math.cos(angle) * radius, y: height / 2 + Math.sin(angle) * radius }); } return state.positions.get(node.id); }
function draw() { const canvas = $('#network-canvas'); if (!canvas) return; const ctx = canvas.getContext('2d'); const width = canvas.clientWidth; const height = canvas.clientHeight; ctx.clearRect(0, 0, width, height); if (state.mode === 'degrees') return drawDegrees(ctx, width, height); const ranked = [...state.nodes].sort((a, b) => b.totalDegree - a.totalDegree); const positions = new Map(ranked.map((node, index) => [node.id, getPosition(node, index, width, height)])); ctx.strokeStyle = 'rgba(23,23,26,.13)'; ctx.lineWidth = .7; state.edges.forEach(({ source, target }) => { const a = positions.get(source); const b = positions.get(target); if (a && b) { ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); } }); ranked.forEach((node) => { const point = positions.get(node.id); const radius = node.totalDegree ? Math.min(11, 2.2 + Math.sqrt(node.totalDegree) * .55) : 1.7; ctx.beginPath(); ctx.arc(point.x, point.y, radius, 0, Math.PI * 2); ctx.fillStyle = node.inDegree > 30 ? '#ef5a44' : node.totalDegree === 0 ? '#9ca5a0' : '#17171a'; ctx.fill(); if (node.inDegree > 42) { ctx.font = '10px DM Mono'; ctx.fillStyle = '#17171a'; ctx.fillText(node.name, point.x + radius + 4, point.y + 3); } }); }
function drawDegrees(ctx, width, height) { const sorted = [...state.nodes].sort((a, b) => b.inDegree - a.inDegree).slice(0, 20); const max = sorted[0]?.inDegree || 1; const barWidth = width / sorted.length * .67; ctx.font = '9px DM Mono'; sorted.forEach((node, index) => { const barHeight = node.inDegree / max * (height - 70); const x = index * (width / sorted.length) + 8; const y = height - barHeight - 35; ctx.fillStyle = index < 3 ? '#ef5a44' : '#17171a'; ctx.fillRect(x, y, barWidth, barHeight); ctx.save(); ctx.translate(x + 5, height - 26); ctx.rotate(-Math.PI / 4); ctx.fillStyle = '#17171a'; ctx.fillText(node.name.slice(0, 14), 0, 0); ctx.restore(); }); ctx.fillStyle = '#706f6a'; ctx.fillText('incoming links / top 20', 12, 18); }
document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-view]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); state.mode = button.dataset.view; $('#chart-title').textContent = state.mode === 'network' ? 'The loudest names' : 'A ranking with a long tail'; $('#chart-caption').textContent = state.mode === 'network' ? 'Nodes sized by total degree. Switch views to compare the graph.' : 'Incoming links, sorted. The first three are highlighted.'; draw(); }));
window.addEventListener('resize', () => { resizeCanvas(); draw(); }); loadData().catch((error) => { $('#loading').textContent = 'Could not load the snapshot.'; console.error(error); });